CFLAGS = -Wall -Wextra -std=gnu11 


structs: structs.c
	gcc $(CFLAGS) -o structs.out structs.c
	./structs.out

strings: strings.c
	gcc $(CFLAGS) -o strings.out strings.c
	./strings.out

clean: 
	rm *.out